"""
Serve the bilingual IPP chatbot through a FastAPI application.

This module initializes the chat engine and exposes API endpoints for
streaming chat responses, managing conversations, generating conversation
titles, and checking service health. It acts as the backend interface between
the frontend and the retrieval-augmented chatbot pipeline.

Run:
    uvicorn api.main:app --reload
    # or: python -m api.main
"""

from __future__ import annotations

import asyncio
import io
import json
import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor
from contextlib import asynccontextmanager
from typing import AsyncGenerator

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(
        sys.stdout.buffer, encoding="utf-8", errors="replace"
    )
    sys.stderr = io.TextIOWrapper(
        sys.stderr.buffer, encoding="utf-8", errors="replace"
    )

from dotenv import load_dotenv

load_dotenv()

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from sse_starlette.sse import EventSourceResponse

from api.database import (
    add_message,
    create_conversation,
    delete_conversation,
    get_conversation,
    get_messages,
    init_db,
    list_conversations,
    update_conversation_title,
)
from chatbot.engine import ChatEngine, ANSWER_MODEL

# ── Global engine (loaded once at startup) ───────────────────────────

_engine: ChatEngine | None = None

# Dedicated thread-pool for blocking I/O so we never starve the event loop.
_io_pool = ThreadPoolExecutor(max_workers=4, thread_name_prefix="rag-io")

# Safety ceiling for the retrieval step (seconds).
RETRIEVAL_TIMEOUT = 60


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _engine
    print("Starting up — loading RAG pipeline …")
    init_db()
    _engine = ChatEngine()
    print("API ready.")
    yield
    _io_pool.shutdown(wait=False)
    print("Shutting down.")


app = FastAPI(
    title="Iran Prosperity Project — RAG Chatbot API",
    description=(
        "Bilingual (English/Persian) RAG chatbot for the IPP Emergency Phase Booklet. "
        "Dense retrieval (Cohere embed-multilingual-v3.0 + Qdrant) with Cohere "
        "rerank-v3.5, answers generated by Gemini Flash-Lite."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# ── CORS — allow any frontend to connect ─────────────────────────────

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Request / Response models ────────────────────────────────────────

class ChatRequest(BaseModel):
    question: str = Field(..., min_length=1, max_length=2000)
    conversation_id: str | None = Field(
        None, description="Existing conversation ID. Omit to create a new one."
    )


class SourceOut(BaseModel):
    white_paper: str
    page_start: int
    page_end: int
    rerank_score: float
    retrieval_source: str
    language: str = "en"


class ChatMessageOut(BaseModel):
    role: str
    content: str
    sources: list[SourceOut] = Field(default_factory=list)
    provider: str = ""


class ConversationOut(BaseModel):
    id: str
    title: str
    language: str
    created_at: str
    updated_at: str


class ConversationDetailOut(ConversationOut):
    messages: list[ChatMessageOut] = Field(default_factory=list)


class RenameRequest(BaseModel):
    title: str = Field(..., min_length=1, max_length=200)


class HealthOut(BaseModel):
    status: str
    engine_loaded: bool
    providers: list[str]


def _generate_chat_title_llm(prompt: str) -> str:
    """Blocking: short chat title via the engine LLM (Gemini)."""
    if _engine is None:
        raise RuntimeError("Engine not loaded")
    text, _provider = _engine._call_llm(
        "You generate short chat titles. Output only the title.",
        "",
        prompt,
    )
    return text


# ── POST /api/chat — streaming answer ────────────────────────────────

@app.post("/api/chat")
async def chat(req: ChatRequest):
    """Stream a chatbot answer via Server-Sent Events (SSE).

    All RAG logic (language detection, classification, retrieval,
    confidence/refusal, prompt selection, source filtering) lives in
    ``ChatEngine``.  This endpoint only handles transport (SSE) and
    persistence (conversation history + messages).

    Events emitted (SSE ``event`` name + JSON ``data``):
      - token    data={"text": "…"}        streamed answer chunks
      - replace  data={"text": "…"}        full answer with USED_PASSAGES stripped (optional)
      - sources  data={"sources": [...]}   sources actually used (or [] for refusals)
      - done     data={"conversation_id":"…", "provider": "…"}
    """
    if _engine is None:
        raise HTTPException(503, "Engine not loaded yet")

    conv_id = req.conversation_id
    if conv_id:
        if not get_conversation(conv_id):
            raise HTTPException(404, f"Conversation {conv_id} not found")
    else:
        conv = create_conversation()
        conv_id = conv["id"]

    add_message(conv_id, "user", req.question)

    def _maybe_set_title() -> None:
        conv = get_conversation(conv_id)
        if conv and not conv["title"]:
            update_conversation_title(conv_id, req.question[:80])

    async def event_stream() -> AsyncGenerator[dict, None]:
        loop = asyncio.get_event_loop()

        # Build conversation history (excluding the just-added user message).
        prev_msgs = get_messages(conv_id, limit=10)
        if prev_msgs and prev_msgs[-1]["role"] == "user":
            prev_msgs = prev_msgs[:-1]
        history_lines = [
            f"{'User' if m['role'] == 'user' else 'Assistant'}: {m['content'][:500]}"
            for m in prev_msgs
        ]
        history_text = "\n".join(history_lines)

        # ── Plan: retrieve → build context (blocking, in pool) ──
        try:
            plan = await asyncio.wait_for(
                loop.run_in_executor(
                    _io_pool, _engine.plan, req.question, history_text
                ),
                timeout=RETRIEVAL_TIMEOUT,
            )
        except (asyncio.TimeoutError, Exception) as e:  # noqa: BLE001
            print(f"  Planning/retrieval failed: {e}")
            lang_guess = "fa" if any("\u0600" <= c <= "\u06FF" for c in req.question) else "en"
            err_msg = (
                "⚠️ The search encountered an error. Please try again."
                if lang_guess == "en"
                else "⚠️ خطایی در جستجو رخ داد. لطفاً دوباره امتحان کنید."
            )
            yield {"event": "token", "data": json.dumps({"text": err_msg}, ensure_ascii=False)}
            add_message(conv_id, "assistant", err_msg, "[]", "error")
            yield {"event": "sources", "data": json.dumps({"sources": []}, ensure_ascii=False)}
            yield {"event": "done", "data": json.dumps({"conversation_id": conv_id})}
            return

        # ── Greeting / low-confidence refusal: emit and finish ──
        if plan.kind in ("greeting", "lowconf"):
            provider = "greeting" if plan.kind == "greeting" else ""
            yield {"event": "token", "data": json.dumps({"text": plan.early_text}, ensure_ascii=False)}
            yield {"event": "sources", "data": json.dumps({"sources": plan.early_sources}, ensure_ascii=False)}
            add_message(
                conv_id, "assistant", plan.early_text,
                json.dumps(plan.early_sources, ensure_ascii=False), provider,
            )
            _maybe_set_title()
            yield {"event": "done", "data": json.dumps({"conversation_id": conv_id, "provider": provider})}
            return

        # ── Stream the answer ──
        provider_holder: list[str] = []
        full_text = ""
        try:
            for chunk in _engine.stream_answer(plan, provider_holder):
                full_text += chunk
                yield {"event": "token", "data": json.dumps({"text": chunk}, ensure_ascii=False)}
                await asyncio.sleep(0)
        except Exception as e:  # noqa: BLE001
            print(f"  Generation failed: {e}")
            err_msg = (
                "⚠️ The answer could not be generated. Please try again."
                if plan.lang == "en"
                else "⚠️ پاسخ تولید نشد. لطفاً دوباره امتحان کنید."
            )
            yield {"event": "token", "data": json.dumps({"text": err_msg}, ensure_ascii=False)}
            add_message(conv_id, "assistant", err_msg, "[]", "error")
            yield {"event": "sources", "data": json.dumps({"sources": []}, ensure_ascii=False)}
            yield {"event": "done", "data": json.dumps({"conversation_id": conv_id})}
            return

        provider = provider_holder[0] if provider_holder else ANSWER_MODEL
        clean_text, sources_out = _engine.finalize(full_text, plan)

        if clean_text != full_text:
            yield {"event": "replace", "data": json.dumps({"text": clean_text}, ensure_ascii=False)}
        yield {"event": "sources", "data": json.dumps({"sources": sources_out}, ensure_ascii=False)}

        add_message(
            conv_id, "assistant", clean_text,
            json.dumps(sources_out, ensure_ascii=False), provider,
        )
        _maybe_set_title()
        yield {
            "event": "done",
            "data": json.dumps({"conversation_id": conv_id, "provider": provider}),
        }

    return EventSourceResponse(event_stream())


# ── Conversation CRUD ────────────────────────────────────────────────

@app.post("/api/conversations", response_model=ConversationOut)
async def create_conv():
    """Create a new empty conversation."""
    return create_conversation()


@app.get("/api/conversations", response_model=list[ConversationOut])
async def list_convs(limit: int = 50):
    """List conversations, most recent first."""
    return list_conversations(limit)


@app.get("/api/conversations/{conv_id}", response_model=ConversationDetailOut)
async def get_conv(conv_id: str):
    """Get a conversation with all its messages."""
    conv = get_conversation(conv_id)
    if not conv:
        raise HTTPException(404, "Conversation not found")

    msgs = get_messages(conv_id)
    messages = []
    for m in msgs:
        sources = []
        try:
            sources = json.loads(m["sources"])
        except (json.JSONDecodeError, TypeError):
            pass
        messages.append(ChatMessageOut(
            role=m["role"],
            content=m["content"],
            sources=[SourceOut(**s) for s in sources] if sources else [],
            provider=m.get("provider", ""),
        ))

    return ConversationDetailOut(
        id=conv["id"],
        title=conv["title"],
        language=conv["language"],
        created_at=conv["created_at"],
        updated_at=conv["updated_at"],
        messages=messages,
    )


@app.patch("/api/conversations/{conv_id}", response_model=ConversationOut)
async def rename_conv(conv_id: str, req: RenameRequest):
    """Rename a conversation."""
    if not get_conversation(conv_id):
        raise HTTPException(404, "Conversation not found")
    update_conversation_title(conv_id, req.title)
    return get_conversation(conv_id)


@app.delete("/api/conversations/{conv_id}")
async def delete_conv(conv_id: str):
    """Delete a conversation and all its messages."""
    if not delete_conversation(conv_id):
        raise HTTPException(404, "Conversation not found")
    return {"deleted": True}


# ── Title generation ──────────────────────────────────────────────────

class TitleRequest(BaseModel):
    question: str
    answer: str


@app.post("/api/generate-title")
async def generate_title(req: TitleRequest):
    """Use Gemini to generate a short chat title from Q&A.

    Detects Persian Q&A and generates a Persian title accordingly.
    """
    if _engine is None:
        raise HTTPException(503, "Engine not loaded yet")

    qa_lang = _engine._detect_language(req.question + " " + req.answer[:200])

    if qa_lang == "fa":
        prompt = (
            "یک عنوان بسیار کوتاه (۳ تا ۶ کلمه) به فارسی برای این گفتگو بنویسید. "
            "عنوان باید موضوع را نشان دهد، نه یک جمله کامل باشد. "
            "فقط عنوان را بنویسید، بدون هیچ توضیح اضافه‌ای. بدون گیومه.\n\n"
            f"کاربر پرسید: {req.question}\n"
            f"پاسخ ربات: {req.answer[:200]}\n\n"
            "عنوان:"
        )
    else:
        prompt = (
            "Generate a very short title (3-6 words max) for a chat conversation "
            "based on this exchange. The title should capture the TOPIC, not be a "
            "sentence. Output ONLY the title, nothing else. No quotes, no punctuation.\n\n"
            f"User asked: {req.question}\n"
            f"Bot answered: {req.answer[:200]}\n\n"
            "Title:"
        )
    try:
        loop = asyncio.get_event_loop()
        raw = await asyncio.wait_for(
            loop.run_in_executor(_io_pool, _generate_chat_title_llm, prompt),
            timeout=15,
        )
        title = raw.strip().strip('"').strip("'")
        if not title:
            return {"title": req.question[:40]}
        if len(title) > 60:
            title = title[:57] + "…"
        return {"title": title}
    except Exception:
        return {"title": req.question[:40]}


# ── Health check ─────────────────────────────────────────────────────

@app.get("/api/health", response_model=HealthOut)
async def health():
    providers = []
    if _engine and _engine._gemini_key:
        providers.append(ANSWER_MODEL)

    status = "ok" if _engine else "loading"

    return HealthOut(
        status=status,
        engine_loaded=_engine is not None,
        providers=providers,
    )


# ── Run directly ─────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "api.main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
    )
