export const API_BASE = import.meta.env.VITE_API_URL || "http://127.0.0.1:8000";

// Public-asset paths must include the configured Vite base prefix so they
// resolve correctly both in dev (/assistant/pdfs/…) and in production
// (https://iranprosperityproject.com/assistant/pdfs/…).
const ASSET_BASE = import.meta.env.BASE_URL;

export const PDFS = {
  en: {
    label: "Emergency Phase — English",
    file: `${ASSET_BASE}pdfs/Emergency_Phase_ENGLISH_20260301_1440.pdf`,
    pages: 178,
  },
  fa: {
    label: "مرحله اضطراری — فارسی",
    file: `${ASSET_BASE}pdfs/Emergency_Phase_PERSIAN_20260301_1440.pdf`,
    pages: 194,
  },
};

export const i18n = {
  en: {
    newChat: "New Chat",
    chats: "Chats",
    documents: "Documents",
    askPlaceholder: "Ask a question about the Iran Prosperity Plan…",
    disclaimer: "IPP Assistant can make mistakes. Please verify important information with the source documents.",
    send: "Send",
    sources: "Sources",
    noAnswer: "I don't have enough information to answer this question.",
    thinking: "Searching documents…",
    welcome: "Ask anything about the Iran Prosperity Plan",
    welcomeSub: "Get cited answers from the Emergency Phase Booklet in English or Persian.",
    page: "p.",
    pages: "pp.",
    score: "score",
    poweredBy: "",
    settings: "Settings",
    deleteChat: "Delete",
    pdfPages: "pages",
    copy: "Copy",
    copied: "Copied",
    edit: "Edit",
    saveEdit: "Save & Send",
    cancelEdit: "Cancel",
    like: "Good response",
    dislike: "Bad response",
    regenerate: "Regenerate",
    pdfBarTitle: "IPP Assistant — Iran Prosperity Plan",
    documentsIntro: "Download the Emergency Phase booklets used by this assistant.",
    downloadPdf: "Download PDF",
    closeDocuments: "Close",
    errorTitle: "Connection error",
    errorBody: "Please try again later.",
  },
  fa: {
    newChat: "گفتگوی جدید",
    chats: "گفتگوها",
    documents: "اسناد",
    askPlaceholder: "سؤال خود را درباره پروژه شکوفایی ایران بپرسید…",
    disclaimer: "دستیار IPP ممکن است اشتباه کند. لطفاً اطلاعات مهم را با اسناد اصلی بررسی کنید.",
    send: "ارسال",
    sources: "منابع",
    noAnswer: "اطلاعات کافی برای پاسخ به این سؤال وجود ندارد.",
    thinking: "در حال جستجوی اسناد…",
    welcome: "هر چه درباره پروژه شکوفایی ایران می‌خواهید بدانید، بپرسید",
    welcomeSub: "پاسخ‌های مستند از کتابچه مرحله اضطراری، به فارسی یا انگلیسی",
    page: "ص.",
    pages: "صص.",
    score: "امتیاز",
    poweredBy: "",
    settings: "تنظیمات",
    deleteChat: "حذف",
    pdfPages: "صفحه",
    copy: "کپی",
    copied: "کپی شد",
    edit: "ویرایش",
    saveEdit: "ذخیره و ارسال",
    cancelEdit: "لغو",
    like: "پاسخ خوب",
    dislike: "پاسخ بد",
    regenerate: "تولید مجدد",
    pdfBarTitle: "دستیار IPP — پروژه شکوفایی ایران",
    documentsIntro: "دانلود کتابچه‌های مرحله اضطراری که این دستیار از آن‌ها استفاده می‌کند.",
    downloadPdf: "دانلود PDF",
    closeDocuments: "بستن",
    errorTitle: "خطا در ارتباط",
    errorBody: "لطفاً بعداً دوباره امتحان کنید.",
  },
};
